// <auto-generated />
using CathysCookbookAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CathysCookbookAPI.Migrations
{
    [DbContext(typeof(CookbookContext))]
    [Migration("20240823192025_AddCompositeKeyToRecipeDetail")]
    partial class AddCompositeKeyToRecipeDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("CathysCookbookAPI.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IngredientID");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientId");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("CathysCookbookAPI.Models.IngredientClass", b =>
                {
                    b.Property<int>("IngredientClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IngredientClassID");

                    b.Property<string>("IngredientClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientClassId");

                    b.ToTable("ingredient_class", (string)null);
                });

            modelBuilder.Entity("CathysCookbookAPI.Models.List", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListName")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ListId");

                    b.HasIndex(new[] { "ListId" }, "IX_lists_ListId")
                        .IsUnique();

                    b.ToTable("lists", (string)null);
                });

            modelBuilder.Entity("CathysCookbookAPI.Models.MeasurementUnit", b =>
                {
                    b.Property<int>("MeasurementId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MeasurementID");

                    b.Property<string>("MeasurementName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MeasurementId");

                    b.ToTable("measurement_units", (string)null);
                });

            modelBuilder.Entity("CathysCookbookAPI.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RecipeID");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RecipeClassID");

                    b.Property<string>("RecipeTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId");

                    b.HasIndex(new[] { "RecipeId" }, "IX_recipes_RecipeID")
                        .IsUnique();

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("CathysCookbookAPI.Models.RecipeClass", b =>
                {
                    b.Property<int>("RecipeClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RecipeClassID");

                    b.Property<string>("RecipeClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeClassId");

                    b.ToTable("recipe_class", (string)null);
                });

            modelBuilder.Entity("CathysCookbookAPI.Models.RecipeDetail", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RecipeID");

                    b.Property<int>("RecipeSeqNo")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("IngredientClassId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IngredientClassID");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IngredientID");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MeasurementID");

                    b.HasKey("RecipeId", "RecipeSeqNo");

                    b.ToTable("recipe_details", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
